version: '3'
services:
  app:
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    build: 
      context: .
      args:
        - CI_USER_TOKEN=${CI_USER_TOKEN}

    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
