# Generated by Django 3.2 on 2021-04-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_data_visual', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=75)),
                ('date', models.DateField()),
                ('confirmed', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='vaccinedata',
            old_name='country_region',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='vaccinedata',
            name='people_fully_vaccinated',
        ),
        migrations.RemoveField(
            model_name='vaccinedata',
            name='people_partially_vaccinated',
        ),
        migrations.RemoveField(
            model_name='vaccinedata',
            name='report_date_string',
        ),
        migrations.RemoveField(
            model_name='vaccinedata',
            name='uid',
        ),
    ]
